#+title: Charming Manual
#+author: Daniel 'jackdaniel' Kochmański
#+email: daniel@turtleware.eu

* Introduction

"Charming" is a display server abstraction built on top of the ECMA-48
standard with using a few popular extensions. The purpose of this project is
to fun and to show-off, qualities which are quickly disappearing from the
professional programming setting. The library proposes multiple (and mutually
exclusive) APIs which are layered on top of each other.

- level0 :: direct manipulation of the terminal
- level1 :: buffered input-output with the state memoization
- level2 :: stateful input-output processing
- level3 :: the frame manager and a sample toolkit

This manual will go through each abstraction and explain how to use it.

* Level 0: Terminal

The terminal is our application's peer on the other side of the stream.
Hopefully it is a terminal emulator which implements common extensions like
the pointer events so it may be configured and used as an interaction device
with the user.

** Initializing the terminal

Communication with the terminal is done with a stream bound to the variable
~*terminal*~ by the programmer. The terminal must be initialized and closed
after use. For instance when the stream attached to the terminal is bound to
the variable ~*terminal-io*~, the whole terminal session looks like this:

#+BEGIN_SRC lisp
  (let* ((*terminal* *terminal-io*)
         (handler (l0:init-terminal)))
    (unwind-protect (run)
      (l0:close-terminal handler)))
#+END_SRC

Where ~run~ is the function which actually works with the terminal.

** Manipulating the cursor

The cursor position may be set to arbitrary row and column, or may be moved
relative to the current position. The function ~set-cursor-position~ accepts
two arguments: row and column, while functions ~cursor-up~, ~cursor-down~,
~cursor-right~ and ~cursor-left~ each accept one argument denoting how many
characters up the cursor should move. For instance:

#+BEGIN_SRC lisp
  (l0:set-cursor-position 12 42) ; row 12, col 42
  (l0:cursor-up 3)               ; row  9, col 42
#+END_SRC

The cursor position may be stored and restored later after some other
operations are done. Calling ~save-cursor-position~ saves the current position
until ~restore-cursor-position~ is called, which restores it.

The macro ~with-cursor-position~ combines functions ~set-cursor-position~,
~save-cursor-position~ and ~restore-cursor-position~ to allow temporary change
of the cursor position. After the body of a macro is executed, the old cursor
position is restored.

#+BEGIN_SRC lisp
  (l0:with-cursor-position (10 23)
    (do-something))
#+END_SRC

The function ~set-cursor-visibility~ is used to control the cursor visibility.
The function accepts one argument which is a generalized boolean.

** Clearing the terminal

The terminal may be cleared in three ways.

1. ~reset-terminal~ is most drastic for it clears the terminal and resets all
   attributes including the cursor position.

2. ~clear-terminal~ is more fine-grained and provides three modes:
   - 0 :: clear from the cursor position to the end of the display
   - 1 :: clear from the cursor position to the start of the display
   - 2 :: clear entire display (default)

3. ~clear-line~ operates on a line and also has three modes:
   - 0 :: clear from the cursor position to the end of the line
   - 1 :: clear from the cursor position to the start of the line
   - 2 :: clear entire line (default)

** Writing on the terminal

Drawing on the terminal is done by putting characters in the terminal
cells. Each written character may have attributes: the foreground and the
background colors and the text style.

Colors are set with RGBA 4-byte values. The alpha value is ignored and colors
are assumed to be opaque. To set colors:

- ~set-foreground-color~ :: sets the foreground color
- ~set-background-color~ :: sets the background color

Text attributes are configured with a function ~set-text-style~ which argument
is a plist with the following keys and valid values:
- intensity :: ~:faint :normal :bold~
- underline :: ~:none :single :double~
- italicized :: generalized boolean
- blink      :: generalized boolean
- inverse    :: generalized boolean
- invisible  :: generalized boolean
- crossout   :: generalized boolean

To write some text on the console use the function ~put~ which accepts any
number of arguments and writes them aesthetically to the terminal. It is
necessary to call ~finish-output~ on the ~*terminal*~ to flush buffers.

Example:

#+BEGIN_SRC lisp
  (l0:set-foreground-color #x884444ff)
  (l0:set-text-style '(:intensity :bold :blink t))
  (l0:put "Hello world!")
  (finish-output l0:*terminal*)
#+END_SRC

** Tracking the pointer

This uses xterm extension implemented by various terminal emulators. To start
tracking the mouse pointer events, call the function ~set-mouse-tracking~. Its
only argument is a generalized boolean which which indicates whether tracking
should be enabled.

Example:

#+BEGIN_SRC lisp
  (set-mouse-tracking t)
  (loop for event = (l0:read-input t)
        when (typep event 'l0:pointer-event)
          do (set-cursor-position (row event) (col event))
             (finish-output *terminal*))
#+END_SRC

** Requests

Requests are processed asynchronously. First the request is sent, and then
after some time a corresponding event is read. In examples in this section we
ignore all events until the response is read, so they are not very practical.

It is important to keep in mind, that requests may be buffered, so in order to
"make them happen" it is necessary to call ~finish-output~ or ~force-output~
on the ~*terminal*~ stream variable after the request, if immedietely after
the loop waiting for the event follows. Otherwise the application may hang
waiting for the input which will never arrive.

*** Cursor position

To request the current cursor position call the function
~request-cursor-position~.

Response depends on the value of a variable ~*request-terminal-size*~:
- T   :: the response event type is ~terminal-resize-event~
- NIL :: the response event type is ~cursor-position-event~

This is to allow querying the terminal size by setting the cursor position to
a large value and requesting its position - the terminal will clamp the
position to the last row and column. For instance:

#+BEGIN_SRC lisp
  (defun get-terminal-size (&aux (l0:*request-terminal-size* t))
    (loop initially (l0:with-cursor-position (32000 32000)
                      (l0:request-cursor-position))
                    (finish-output l0:x*terminal*)
          for event = (l0:read-input t)
          when (typep event 'l0:terminal-resize-event)
            do (return-from get-terminal-size
                 (values (l0:rows event) (l0:cols event)))))

  (defun get-cursor-position (&aux (l0:*request-terminal-size* nil))
    (loop initially (l0:request-cursor-position)
                    (finish-output l0:*terminal*)
          for event = (l0:read-input t)
          when (typep event 'l0:cursor-position-event)
            do (return-from get-cursor-position
                 (values (l0:row event) (l0:col event)))))
#+END_SRC

** Processing the input

To read input it is enough to call the function ~read-input~. The function
returns either NIL, when no input is available, or an instance of the class
~event~. The function accepts one argument ~waitp~, which indicates whether
the function should wait for input if none is present, or immedietely return.

*** event

This class is a superclass of all events.

*** terminal-event (event)

This class is a superclass of all events which represent control sequences
send by the terminal.

*** unknown-terminal-event (terminal-event)

When the terminal produces a sequence which can't be parsed, then instance of
this class is returned. The sequence may be read from the event with a reader
~seq~.

*** cursor-position-event (terminal-event)

When the programmer calls ~request-cursor-position~, then the terminal will
produce a sequence which will be parse to this class instance. This event has
two readers ~row~ and ~col~, which indicate the current cursor position.

*** terminal-resize-event (terminal-event)

When the programmer calls ~request-cursor-position~ with a variable
~*request-terminal-size*~ bound to ~T~, then the terminal will produce a
sequence which will be parsed to this class instance. This event has two
readers ~rows~ and ~cols~, which indicate the screen dimensions.

It is not defined whether this event may happen without prior call to the
function ~request-cursor-position~ with ~*request-terminal-size~ = ~T~.

*** keyboard-event (event)

Keyboard event represents a pressed key and modifiers being pressed at that
time. The event has three readers: ~key~ representing the pressed key, ~kch~
representing the pressed character or NIL if the key does not represent one
and ~mods~ representing pressed modifiers.

The event is accompanied with a predicate ~keyp~ which may be used to check
whether the keyboard event matches a key combination. For instance:

#+BEGIN_SRC lisp
  (keyp event :f1 :M :C) ; Ctrl + Meta + F1
  (keyp event :f1 :A :C) ; Ctrl + Alt + F1
  (keyp event #\S)       ; Shift + s
  (keyp event :f1 :s)    ; Shift + F1
#+END_SRC

The predicate may be used with other types of events in which case it will
return NIL.

The function ~set-alt-is-meta~ may be used to map the key Alt to Meta (that
is, when the reported modifier is Alt, the library will treat it as Meta). For
instance:

#+BEGIN_SRC lisp
  (set-alt-is-meta t)   ; Alt is treated as Meta
  (set-alt-is-meta nil) ; Alt is treated as Alt
#+END_SRC

Currently recognized non-ascii keys are: ~:home~, ~:insert~, ~:delete~,
~:end~, ~:page-up~, ~:page-down~, ~:f1~ up to ~:f20~, ~:key-up~, ~:key-down~,
~:key-right~, ~:key-left~, ~:escape~ and ~:delete~.

Moreover ~rubout~ and ~backspace~ are returned for ~C-?~ and ~C-h~. Which one
is send when the key "backspace" is pressed depends on the terminal.

Note, that the window manager or the terminal application may not send some
keys to the application, for instance Alt+Number may be reserved for switching
tabs and ~:f1~ may be mapped to open the "Help" menu.

*** pointer-event (event)

Pointer event represents an event produced by a pointer manipulation when the
pointer tracking is on. The event has five readers: ~row~ and ~col~ which
indicate the pointer position, ~btn~ representing the pointer button, ~mods~
representing pressed modifiers and ~state~ which denotes the kind of event.

~btn~ is one of ~:none~, ~:left~, ~:middle~, ~:right~, ~:wheel-up~,
~:wheel-down~, ~:wheel-left~, ~:wheel-right~, ~:extra-1~, ~:extra-2~,
~:extra-3~ and ~:extra-4~.

~state~ is one of ~:motion~, ~:press~ and ~:release~.

* Level 1: Console

The console is an instance of the class ~console~ which is used as an
intermediate between the programmer and the terminal. Its purpose is to
maintain the current terminal state in the application memory, abstract away
common operations and minimize the I/O bandwidth.

** Initializing the console

The quickest way to start working with a console is to initialize it and draw
a things on it. To create a console use the macro ~with-console~:

#+BEGIN_SRC lisp
(l1:with-console (:ios *terminal-io* :mode :dir)
  (l1:out (:row 4 :col 8) "Hello world!")
  (l1:process-next-event t)
  (l1:exit))
#+END_SRC

The macro estabilishes a dynamic context in which the input is remembered (see
the section "Cursors") and the output may be buffered based on the rendering
mode (see the section "Buffers").

Input is read with the function ~process-next-event~ which has the same
semantics as the function ~read-input~ in the level 0 abstraction and should
be called instead (because it also updates the console state and calls the
function ~handle-event~ which may be optionally specialized by clients).

** Text styles

A text style is an opaque object constructed with the operator
~make-text-style~. The following keywords / values paris are valid:

- intensity  :: ~:normal :faint :bold~
- underline  :: ~:none :single :double~
- italicized :: generalized boolean
- blink      :: generalized boolean
- inverse    :: generalized boolean
- invisible  :: generalized boolean
- crossout   :: generalized boolean

For instance to create a text style for a bold text with inversed color:

#+BEGIN_SRC lisp
  (make-text-style :intensity :bold :inverse t)
#+END_SRC

Unspecified elements are taken from the text style ~*default-text-style*~
which default values are the first value elements in the keywords / values
list above. To change the default text style before drawing the variable
should be bound to a complete text style.

To produce a complete text style call ~fuze-text-style~. The second argument
to the function defaults to ~*default-text-style~ which is always complete.
Binding ~*default-text-style~ to the incomplete text style has undefined
consequences.

#+BEGIN_SRC lisp
  (fuze-text-style (make-text-style :italicized t))
#+END_SRC

To compare two text styles call ~text-style-equal~ which returns either a
boolean.

#+BEGIN_SRC lisp
  (text-style-equal style-1 style-2)
#+END_SRC

** Cursors

Cursor can have multiple purposes:

- pen      :: defines a drawing style
- position :: stores current row and column
- input    :: stores data associated with a cursor
- marker   :: directs user attention at the cell
- pointer  :: selects a cell in the buffer

The cursor protocol:

- cursor-enabledp, change-cursor-enabledp   :: gf (is cursor enabled?)
- cursor-visiblep, change-cursor-visiblep   :: gf (visibility)
- cursor-position, change-cursor-position   :: gf (position in the buffer)
- cursor-inks,     change-cursor-inks       :: gf (color)
- cursor-text,     change-cursor-text       :: gf (text style)
- cursor-data,     change-cursor-data       :: gf (cursor-specific data)
- cursor                                    :: class
- :cep :cvp :row :col :fgc :bgc :txt :obj   :: initargs

It is up to the buffer owning the cursor to update its state and to honor
flags like ~enabledp~ or ~visiblep~. The console maintains a few special
purpose cursors: the terminal cursor, the pointer cursor and the virtual
pointer cursor.

At least two cursors are associated with each buffer: a buffer cursor and a
direct cursor. In case of the console a direct cursor is the terminal cursor.

*** Terminal cursor

This cursor represents the physical terminal's cursor. The cursor is moved
when drawing on the terminal is performed, so if the cursor is visible it will
move across the screen when a buffered output is flushed. The original cursor
position is restored after ~flush-output~, but not after ~put-cell~, which
advances the cursor accordingly. The terminal cursor is always enabled and has
no associated data.

*** Pointer cursor

The pointer cursor maintains the last state of the pointer reported by the
terminal. Enabling the pointer sets the mouse tracking. The associated data is
the last pointer event.

The pointer maintains a state which has the same accessors as ~pointer-event~,
however it may be different from the last event. For instance the event
"release, left button" leaves the pointer in a state "motion, no button".

*** Virtual pointer cursor

Not all terminal emulators allow tracking the pointer. In order to mitigate
that state a virtual pointer is implemented which is manipulated with the
keybaord. The associated data is a synthesized pointer event. It is possible
for both pointer cursors to be enabled at the same time.

Available gestures:
- <arrow-key> :: move the pointer
- C-<arrow-key> :: move the pointer with "pressed" left button
- <insert> <center> <delete> :: button click left, middle, right
- <home> <end> <pgup> <pgdn> :: wheel scroll left, right, up, down
- M-<arrow-up> :: reset the cursor position to [1,1]
- M-<arrow-down> :: untoggle all toggled buttons and modifiers
- M-<arrow-left> :: toggle control
- M-<arrow-right> :: toggle meta ; truly meta :_)
- M-<insert> M-<center> M-<delete> :: toggle press left, middle, right
- M-<home> M-<end> M-<pgup> M-<pgdn> :: toggle "extra" buttons 1-4

Only one button may be toggled at the same time (so toggling another button
releases the first one). Moving the cursor with ~C-<arrow-key>~ shadows the
toggled button while moving the cursor with ~<arrow-key>~ restores it.

*** Buffer cursor

Each buffer has its own private cursor which is used in buffered and
write-through rendering mode.

*** Direct cursor

This abstraction level allows both buffered and direct writes. A direct cursor
is the cursor which performs direct operations (from the buffer perspective)
unlike the buffer cursor which writes to its internal memory. Direct cursor is
used when flushing the output and in direct and write-through rendering mode.

For the console a direct cursor is the terminal cursor. For a surface it is
its sink's current cursor and depends on the rendering mode of the sink:

- dir :: sink's direct cursor
- buf :: sink's buffer cursor
- wrt :: sink's buffer cursor

** Buffers

*** Output buffer

~output-buffer~ is an abstract class which implements output buffering and
clipping. Functions specified for all instances of that class are:

- buffer-cursor
- direct-cursor
- flush-output
- put-cell
- set-cell
- mode, (setf mode)
- bbox, rows, cols
- inside-p
- invoke-with-clipping
- resize-buffer

To specify a "current" buffer a macro ~with-buffer~ is specified. Macros
operating on the current buffer are ~ctl~ and ~out~. Additionally a function
~clear-rectangle~ is build on top of the macro ~out~.

A helper class is defined which implements a ~bbox~ protocol, that is accessors
~r1 c1 r2 c2~ which define a bounding box (accessors are keywords with the same
names). The method ~bbox~ specialized on this class returns said four values.

*** Surface

A surface is a parasite output buffer - its direct cursor is in fact a buffer
cursor of its sink (i.e a console or an another output buffer). Surface
subclasses ~bbox~ and ~output-buffer~ and it has its own dimensions (expressed
in the sink coordinates) as well as a scroll offset. For example if we have a
surface with a bounding box ~3 6 5 11~, then it starts at 3rd row and 6th column
and it spans 3 rows and 6 columns. The surface may be much bigger than its
bounding box - the rest is clipped accordingly.

A scroll offset is added to the coordinate, so if the offset is:
- [0,0], then surface's cell [1,1] is located at [r1,c1]
- [2,2], then surface's cell [3,3] is located at [r1,c1]

Surface protocol:

- surface (bbox output-buffer) :: protocol class
- sink :: surface's sink buffer (the parent output buffer))
- bbox :: surface dimensions in its sink's coordinates (values r1 c1 r2 c2)
- offset :: scroll offset (values row col)
- (:row0 0), (:col0 0), :r1, :c1, :r2, :c2, (:sink *buffer*) :: initargs

To determine actual size of the surface it is enough to call appropriate
~output-buffer~ protocol functions.

Helper functions:
- (scroll-surface buf rdx cdx)      :: scrolls the surface
- (move-surface buf rdx cdx)        :: moves the buffer in parent's plane
- (reshape-surface buf r1 c1 r2 c2) :: changes the surface bbox in parent's plane

*** Console

A class ~console~ represents a terminal and adds to it buffering capabilities,
rendering modes and default input processing. Moreover it maintains the terminal
cursor (as its direct cursor), a pointer cursor (a mouse extension) and a
virtual pointer cursor (keyboard-driven fake pointer). ~console~ is a subclass
of ~output-buffer~.

This class is default for ~with-console~ macro and represents a "single" window
for the application. It is possible to specify a different class with the
keyword argument ~console-class~ in the macro ~with-console~. Usually it will be
a subclass of the console.

*** Surface manager

A class ~surface-manager~ is a subclass of the ~console~ and is meant to manage
multiple surfaces. If ~console~ could be considered as a full screen
"application window", then ~surface-manager~ would be a "window manager".

** Hints

*** Drawing the cursor

In order to draw the cursor without modifying a buffer a direct mode should be
used, however that's not enough. When the buffer is flushed it will draw over
the cursor marker and make it invisible again. In order to avoid that, define
an after method for ~flush-output~ and draw the cursor from there.

#+BEGIN_SRC lisp
  (defmethod l1:flush-output :after ((client wool) &rest args)
    (declare (ignore args))
    (multiple-value-bind (row col)
        (l1:cursor-position (my-cursor client))
      (put-cell client "X" :row 42 :col :fgc #xff000000)))
#+END_SRC
